### ISSUE TITLE
LinkedIn Developer Access Denied

### ISSUE THREAD

**Issue by karenwithat** [orbit-love/community-ruby-linkedin-orbit#24]
Hello,

My organization is test-driving Orbit for our developer relations tool. I tried to get access for Orbit + LinkedIn, but it was denied with the following statement:

> We are unable to grant your app access to Marketing Developer Platform at this time. The use-case you provided does not meet the criteria for our supported marketing use-cases.

I also noticed that there appears to be a plug-and-play integration for LinkedIn in the works. Is this the right place to put this issue? Can anyone give any updates?  Thanks.

**Comment by colinloretz** [comment]
Hi @karenwithat! Apologies for that review experience with LinkedIn.

We do have the plug-and-play Linkedin integration becoming available shortly and it will be a much better experience than having to maintain the community integration in your own Github.

We will update this Github repo to reflect the upcoming beta and assist new folks in finding it. Thanks for raising this issue!
